# Generated by Django 2.2.3 on 2019-07-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, default='Fartura', max_length=50, null=True)),
                ('cep', models.CharField(blank=True, default='18870-000', max_length=12, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('nome_do_aluno', models.CharField(max_length=255)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=255)),
                ('modalidade', models.CharField(blank=True, choices=[('musculacao', 'Musculação'), ('crossfit', 'Crossfit'), ('feminino:circuito', 'Circuito [F]'), ('masculino:circuito', 'Circuito [M]')], max_length=30, null=True)),
                ('matriculado', models.BooleanField(default=True, help_text='Este campo será usado para gerar as cobranças mensais. Se o aluno estiver matriculado todo mês vamos gerar uma mensalidade.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, default='Fartura', max_length=50, null=True)),
                ('cep', models.CharField(blank=True, default='18870-000', max_length=12, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('nome_do_funcionario', models.CharField(max_length=255)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('pagamento_recebido', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
