# Generated by Django 2.2.3 on 2019-07-30 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20190726_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('modalidade', models.CharField(blank=True, choices=[('musculacao', 'Musculação'), ('strongman', 'StrongMan'), ('powerlift', 'Powerlift'), ('crossfit', 'Crossfit'), ('feminino:circuito', 'Circuito [F]'), ('masculino:circuito', 'Circuito [M]')], max_length=30, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='modalidade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Plano'),
            preserve_default=False,
        ),
    ]
