# Generated by Django 2.2.3 on 2019-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20190730_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(default='5514', help_text='Preencha como o exemplo: 5514911112222', max_length=20),
        ),
    ]
