# Generated by Django 2.2.3 on 2019-08-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20190802_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(default='55149', help_text='Preencha como o exemplo: 55149XXXXXXXX', max_length=13),
        ),
    ]
