# Generated by Django 2.2.3 on 2019-08-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_auto_20190802_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(max_length=20, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDaPlanilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticao', models.IntegerField(blank=True, null=True)),
                ('tecnica', models.CharField(blank=True, max_length=255, null=True)),
                ('tabela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Planilha')),
            ],
        ),
    ]
