# Generated by Django 2.2.3 on 2019-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_itemdaplanilha_planilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdaplanilha',
            name='tipo_do_treino',
            field=models.CharField(choices=[('treino_A', 'Treino A'), ('treino_B', 'Treino B'), ('treino_C', 'Treino C')], max_length=30, null=True),
        ),
    ]
