# Generated by Django 2.2.3 on 2019-08-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_itemdaplanilha_tipo_do_treino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('treino_A', 'Treino A'), ('treino_B', 'Treino B'), ('treino_C', 'Treino C'), ('treino_D', 'Treino D'), ('treino_E', 'Treino E'), ('treino_F', 'Treino F')], max_length=30, null=True)),
                ('musculacao', models.CharField(choices=[('treino_A', 'A'), ('treino_B', 'B'), ('treino_C', 'C'), ('treino_D', 'D'), ('treino_E', 'E'), ('treino_F', 'F')], max_length=30, null=True)),
                ('aerobico', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemdaplanilha',
            name='tipo_do_treino',
            field=models.CharField(choices=[('treino_A', 'Treino A'), ('treino_B', 'Treino B'), ('treino_C', 'Treino C'), ('treino_D', 'Treino D'), ('treino_E', 'Treino E'), ('treino_F', 'Treino F')], max_length=30, null=True),
        ),
    ]
