# Generated by Django 2.2.3 on 2019-08-21 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0014_itemdaplanilha_musculatura_do_treino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nome_do_aluno',
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
