# Generated by Django 2.2.3 on 2019-08-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_auto_20190821_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdaplanilha',
            name='tecnica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='periodizacao',
            name='aerobico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
