# Generated by Django 2.2.3 on 2019-08-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_auto_20190821_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdaplanilha',
            name='tipo_do_treino',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='periodizacao',
            name='dia',
            field=models.CharField(choices=[('Seg', 'Seg'), ('Ter', 'Ter'), ('Qua', 'Qua'), ('Qui', 'Qui'), ('Sex', 'Sex'), ('Sab', 'Sab')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='periodizacao',
            name='musculacao',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=30, null=True),
        ),
    ]
